export { default as Navbar } from "./Navbar";
export { default as HomeSection } from "./HomeSection";
export { default as SocmedBox } from "./SocmedBox";
export { default as AboutSection } from "./AboutSection";
export { default as SkillSection } from "./SkillSection";
export { default as WorkSection } from "./WorkSection";
export { default as ContactSection } from "./ContactSection";
export { default as ScrollToTop } from "./ScrollToTop";
export { default as Footer } from "./Footer";
